---
output: github_document
---

# Secondary Analyses of International Large-scale Assessments in Education

- The present is a repository for sharing the workshop materials with attendants

# Slides

- Day 1: From data preparation to data modelling
  + [Introduction to ILSA](https://www.dropbox.com/s/b6jullktpr2k1ul/day_01_part_1_intro.pdf?dl=1)
  + [Data preparation, part 1](https://www.dropbox.com/s/errjks89w4flkeh/day_01_part_2_data_prep.pdf?dl=1)
  + [Data preparation, part 2](https://www.dropbox.com/s/xts1igppk6od75u/day_01_part_3_data_prep.pdf?dl=1)
- Day 2: [...] *to be updated*
- Day 3: [...] *to be updated*
- Day 4: [...] *to be updated*

>Note: press this [link to download all slides in pdf](https://www.dropbox.com/sh/hrajgyb6e31b6cr/AAC2C8fpxlrfQGI70Q9tycy4a?dl=1).

# Workshop examples

## Day 1: Data preparation

- Download the files to replicate the **import and export data for modelling** [example](https://www.dropbox.com/sh/1kxfsumwf2dot07/AAAsOZpI0VghO40SBVPgrzhQa?dl=1).
  + link also [here](https://www.dropbox.com/sh/1kxfsumwf2dot07/AAAsOZpI0VghO40SBVPgrzhQa?dl=1).


## Day 2: Multilevel models

- Download the files to replicate the [**multilevel model examples**](https://www.dropbox.com/sh/3vl7vd85h4qr6ol/AACVtG9U2jRaFCXNir8ZHzVga?dl=1).
  + link also [here](https://www.dropbox.com/sh/3vl7vd85h4qr6ol/AACVtG9U2jRaFCXNir8ZHzVga?dl=1).



## Authors

- Carrasco, D., PhD, Centro de Medición MIDE UC
- Sandoval-Hernández, A., PhD, Univeristy of Bath
- López-Hornickel, N., Doctoral student, Univeristy of Bath


# About

ILSA workshop, An initiative of the Department of Education, University of Bath, funded by the Southwest Doctoral Training Partnership (SWDTP).
